### ISSUE TITLE
Stamm webinterface problem

### ISSUE THREAD

**Issue by jonteohr** [popoklopsi/Stamm-Webinterface#1]
Hello, when I installed stamm webinterface I got this error Table '56fe8a1e01ba911113df73e6.STAMM_DB_1' doesn't exist

It didn't create that table, but it created several other tables. How can I solve this?

**Comment by ghost** [comment]
Not the webinterface creates the stamm database, the stamm plugin on your server should create the stamm database

**Comment by jonteohr** [comment]
It never created that table, I noticed.. So my stamm points resets when server restarts

**Comment by jonteohr** [comment]
Nevermind, it created one just now after server restart xD
